import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy - Memovox',
  description: 'Privacy Policy for Memovox - Protecting your personal data and ensuring you have full control over your information.',
};

export default function PrivacyPolicyPage() {
  return (
    <main className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="space-y-12">
        {/* Header */}
        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight">
            <span className="text-gradient">Privacy Policy</span>
          </h1>
          <p className="text-muted-foreground text-lg">
            Last Updated: December 2025
          </p>
        </div>

        {/* Introduction */}
        <section className="prose prose-invert max-w-none">
          <p className="text-lg leading-relaxed text-gray-300">
            At <strong className="text-white">Memovox</strong>, your privacy matters. We are committed to protecting your personal data and ensuring you have full control over your information. This policy outlines what data we collect, how we use it, and your rights under global privacy laws including GDPR, UK GDPR, CCPA, and CPRA.
          </p>
        </section>

        {/* 1. Data We Collect */}
        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-white border-b border-gray-800 pb-2">
            1. Data We Collect
          </h2>
          <p className="text-gray-300">
            We collect only the information necessary to provide our AI-powered voice companion services:
          </p>
          
          <div className="grid md:grid-cols-2 gap-6">
            <div className="glass p-6 rounded-xl space-y-3">
              <h3 className="text-xl font-medium text-primary">Account Information</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-400">
                <li><strong className="text-gray-200">Email Address:</strong> For authentication and account management.</li>
                <li><strong className="text-gray-200">Name:</strong> To personalize your experience.</li>
                <li><strong className="text-gray-200">Account Creation Date:</strong> For account administration.</li>
              </ul>
            </div>

            <div className="glass p-6 rounded-xl space-y-3">
              <h3 className="text-xl font-medium text-secondary">Voice Recordings & Content</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-400">
                <li><strong className="text-gray-200">Audio Files:</strong> The voice memos you record.</li>
                <li><strong className="text-gray-200">Transcriptions:</strong> Text converted from your audio.</li>
                <li><strong className="text-gray-200">AI Analysis:</strong> Summaries, insights, and chat history generated by our AI.</li>
              </ul>
            </div>

            <div className="glass p-6 rounded-xl space-y-3 md:col-span-2">
              <h3 className="text-xl font-medium text-accent">Usage & Technical Data</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-400">
                <li><strong className="text-gray-200">Usage Patterns:</strong> How you interact with app features.</li>
                <li><strong className="text-gray-200">Device Information:</strong> Technical details about your device (for compatibility and troubleshooting).</li>
                <li><strong className="text-gray-200">Performance Data:</strong> Error logs and crash reports (only if you have enabled crash reporting).</li>
              </ul>
            </div>
          </div>
        </section>

        {/* 2. How We Protect Your Data */}
        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-white border-b border-gray-800 pb-2">
            2. How We Protect Your Data
          </h2>
          <p className="text-gray-300">Your security is our top priority.</p>
          <ul className="grid md:grid-cols-2 gap-4">
            {[
              { title: 'Encryption', desc: 'All data is encrypted in transit using TLS (Transport Layer Security).' },
              { title: 'Secure Storage', desc: 'Your personal data and memos are stored securely.' },
              { title: 'No Data Sales', desc: 'We NEVER sell your data to third parties.', highlight: true },
              { title: 'No Advertising', desc: 'We do not use your personal content for advertising purposes.' },
            ].map((item, idx) => (
              <li key={idx} className="bg-gray-900/50 p-4 rounded-lg border border-gray-800">
                <strong className={item.highlight ? "text-accent" : "text-white"}>{item.title}:</strong> <span className="text-gray-400">{item.desc}</span>
              </li>
            ))}
          </ul>
        </section>

        {/* 3. Third-Party Data Sharing */}
        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-white border-b border-gray-800 pb-2">
            3. Third-Party Data Sharing
          </h2>
          <p className="text-gray-300">
            We partner with trusted services to deliver our features. Here is what they receive:
          </p>
          
          <div className="overflow-x-auto rounded-lg border border-gray-800">
            <table className="w-full text-left text-sm">
              <thead className="bg-gray-900 text-gray-200 font-medium">
                <tr>
                  <th className="p-4">Service</th>
                  <th className="p-4">Purpose</th>
                  <th className="p-4">Data Handled</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-800">
                <tr className="bg-black/20">
                  <td className="p-4 font-medium text-white">AI Processing Providers</td>
                  <td className="p-4 text-gray-400">Transcription & AI Intelligence</td>
                  <td className="p-4 text-gray-400">Processes voice audio (temporarily) and text for analysis. Data is <strong className="text-white">NOT</strong> stored permanently by these providers.</td>
                </tr>
                <tr className="bg-black/20">
                  <td className="p-4 font-medium text-white">Cloud Database Services</td>
                  <td className="p-4 text-gray-400">Database & Authentication</td>
                  <td className="p-4 text-gray-400">Stores account info and encrypted memo data. SOC 2 Type II certified.</td>
                </tr>
                <tr className="bg-black/20">
                  <td className="p-4 font-medium text-white">App Infrastructure Services</td>
                  <td className="p-4 text-gray-400">App Infrastructure</td>
                  <td className="p-4 text-gray-400">Collects anonymous usage stats and crash reports (if enabled).</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* 4. Data Retention Policy */}
        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-white border-b border-gray-800 pb-2">
            4. Data Retention Policy
          </h2>
          <p className="text-gray-300">We keep your data only as long as you need it:</p>
          <ul className="space-y-3 pl-4 border-l-2 border-primary/30">
            <li className="pl-2"><strong className="text-white">Active Account:</strong> <span className="text-gray-400">Data is retained indefinitely while you use the app so you can access your history.</span></li>
            <li className="pl-2"><strong className="text-white">Deleted Account:</strong> <span className="text-gray-400">When you delete your account, your data is <strong className="text-white">immediately purged</strong> from our active systems.</span></li>
            <li className="pl-2"><strong className="text-white">Backups:</strong> <span className="text-gray-400">Residual data in backups is removed within 30 days of account deletion.</span></li>
            <li className="pl-2"><strong className="text-white">Legal Holds:</strong> <span className="text-gray-400">We retain data only if strictly required by law.</span></li>
          </ul>
        </section>

        {/* 5. Your Rights */}
        <section className="space-y-6">
          <h2 className="text-2xl font-semibold text-white border-b border-gray-800 pb-2">
            5. Your Rights (GDPR / CCPA)
          </h2>
          <p className="text-gray-300">You have full control over your data:</p>
          <div className="grid gap-4">
            <div className="bg-gray-900/30 p-4 rounded-lg border border-gray-800">
              <div className="font-semibold text-white mb-1">Right to Access & Portability</div>
              <p className="text-sm text-gray-400">You can export all your data (voice memos, chat sessions, profile, and preferences) at any time as a JSON file directly from the app.</p>
            </div>
            <div className="bg-gray-900/30 p-4 rounded-lg border border-gray-800">
              <div className="font-semibold text-white mb-1">Right to Erasure (Right to be Forgotten)</div>
              <p className="text-sm text-gray-400">You can permanently delete your account and all associated data. This action is irreversible and includes all voice memos, transcriptions, and AI profiles.</p>
            </div>
            <div className="bg-gray-900/30 p-4 rounded-lg border border-gray-800">
              <div className="font-semibold text-white mb-1">Right to Privacy Controls</div>
              <p className="text-sm text-gray-400">You can toggle settings for analytics and crash reporting within the app at any time.</p>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}
